spring.application.name=shop-order

# RabbitMQ??
spring.rabbitmq.host=192.168.231.129
spring.rabbitmq.port=5672
# ??????
spring.rabbitmq.virtual-host=/
# ?????????Broker??
spring.rabbitmq.publisher-confirm-type=correlated
# ?????????Queue??
spring.rabbitmq.publisher-returns=true
# ??????Queue???????????returnfirm
spring.rabbitmq.template.mandatory=true
# ??ack??????????????
spring.rabbitmq.listener.simple.acknowledge-mode=manual

fzyshop.thread.coreSize=20
fzyshop.thread.maxSize=200
fzyshop.thread.keepAliveTime=10

alipay.app_id=9021000161679440
alipay.merchant_private_key=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCLt1FlEMMxlqJTP2W5s+z1E3xvUuuNC29vUvNDEM0R8nNwI2JSRTHMSOlBZVYop47LWDEWPohcVc3qp6m1iGw6Ld0eu3eEVh2AlUXMt5gD8/JQQQhqyVZ9D1JEp9mIgvT+jUR7QNLZnDEdTXe/yTKslIjHJHhAyCGl7YYhpOPAH0CdDR+wTgVQi74CYkY1xMX4940bpnDku/KzlyvQwodILvsFQjAGQpIyX+7FrtoUNEyiPsouJq+6dyjAFHzjnILkwlut/sy8AU3hHON69Ay5DcE3xdgTeixjXQGtyA2SVAV2RtFCVkOYov4bjCB5nce20udogMmd/XNJrB1vBpJLAgMBAAECggEAIhp8HrxJuQf41XMrJHobw/KetBm8b3A0IitQP7WRKOlSbjPk4woKzr+ZWCIhNsk3nMEJMlHPPSKgob+NOEd1i3n4eHDwCnhuuR02rXK/A2//XMGTCWXd26bqwOFrwtuca6oV5jP7g6yRfIKVUVYOLXwQKvPm+oEfXX4t+HZkNVfOtX+s88LCBfAnUC0AMSyDOr1NNwKbt41zLKUnn/jgnGux+UIWib0Za//8AndQPfdV8EE1nBhDP69jaSXDaCO7diYm1HMBs6cJjpAjcsdRjDMJ18Gip7gJns1PAYarxlc8igmWWAYktGF/N9rYBZmcsD5NCimBiczn0Xpqkb0tGQKBgQDSemn6lyAHVvnZLc6HEtqtn24MZ9p8ATjgFaBXZU3gkfAJlTAYtWJr7liHUn17SBuq6c0kIwjUirGJlMabcx/sx65cwxwYXqkTxc/kGSjpP4AKDcvMgJOdZtAlGRMa0RUUN8rxu2ByuEWfrBKNqe/JVgPzK+CcKK9lLdyG2JsY7wKBgQCp7wFlNyRUaXXFx39moxI5ZFSlQ6Ju5J0Q4x+2jl292POUJBp623u+fBS36/6MqEnLYgJl3dSGYzYfDnrjYJftBxy3vhiFLV8vV9AgQOUjYvKtgF6Jl3+W/ZdxVNgR7bO32lngbfjDyyhTSq7ZdRewWY8pW/+0S2r+oKn/Fa4EZQKBgQCaPxPDjVTvjBH10tfzrSGM87WWadV34v1nWvHymk8EMG8U1rw0n1jNeBJwuUc0PZfpHQY1YWdrO2j4Rot2CFxxDbT+Tg4c3eJSlzjPFJEivmJ6+7lK2T9UrrADP+j8UhV8h5a2qHb6G4kKhvPh1ZPgnKSwZItqZXaEU6O1PrALCQKBgCG6nrxIRZ27kPTAtDjbBTL/Bw4Gbqc0GTjQ2+qQN2sHNNGimN7p0ZXtau9WmB+zB3Km8XLmpNhHuOZRKXMYKQ+S6dBOmu9UIiBzfYvpVZHAggqOADWvLFP74aNNA9YLKDDF1jEFouq52DcwC6R96UXHgPLkn8xZa9M+cH+A/hlBAoGBAL73KcyPRtLfiTm5WlapziDrzslUBeWun6kDtQITrVOcIGxkEW0riM1cPiRs2+BbNGSKDW00v2fhtkgfllhNBaAiihngbIrMMfPgf9lbExqsSXA3K30tCegp+NYyXvDyQgn8vU/krgO50atbmFvdopiVxfwxW/6culD/bPDIqctd
alipay.alipay_public_key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiXib7xSdIzLxQs98O7IKvI0TCou7YTBp55kwVUR1t/8mxcMhRB0kAM3MvT+cZ9XIjaPPDZUreJbd1Eqit5+IAmaCqG/8u8eP4PRUsmpXKUA/yFD2FHPn15QGb9KnZ5DmbAlZOXY+V+50lsNrJiyVVeL2rlUomE/D6Pw7FjIjqwVGrFkTYYhLVRsYieY6hzcWEv3dC+ZUH94xg7pwjbcw+mM+kkwkTZudTR7PTS8AQXy6Rv0WmazILLeRDfWT6jRCmvqzVQh+Tk67HBgxooA5cDjeh/WRa5STktIBjERsFWX1CzwdUxP5bOjS8knKHWRo45y7Adq7hgXE3N7KygMqBwIDAQAB
alipay.notify_url=http://r9649a3f.natappfree.cc/pay/notify
alipay.return_url=http://member.fzyshop.com/memberOrder.html
alipay.sign_type=RSA2
alipay.charset=utf-8
alipay.gatewayUrl=https://openapi-sandbox.dl.alipaydev.com/gateway.do

spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss